name: Deploy Frontend, Backend & Nginx to AWS ECR & EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push-frontend:
    name: Build & Push Frontend to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build and Push Frontend
        run: |
          cd 2-sunday-ahn-community-fe-react
          docker buildx build --platform linux/amd64 \
            -f Dockerfile \
            --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
            --build-arg REACT_APP_BACKEND_PORT=${{ secrets.REACT_APP_BACKEND_PORT }} \
            -t ${{ secrets.ECR_REGISTRY }}/sunday/community-frontend:latest --push .

  build-and-push-backend:
    name: Build & Push Backend to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build and Push Backend
        run: |
          cd 2-sunday-ahn-community-be
          docker buildx build --platform linux/amd64 \
            -f Dockerfile \
            -t ${{ secrets.ECR_REGISTRY }}/sunday/community-backend:latest --push .

  build-and-push-nginx:
    name: Build & Push Nginx to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build and Push Nginx
        run: |
          cd nginx
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.ECR_REGISTRY }}/sunday/community-nginx:latest --push .
